version: '3.8'

services:
  # バックエンド（FastAPI）
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: material-memory-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - material-network
    restart: unless-stopped

  # フロントエンド（Next.js）
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: material-memory-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    networks:
      - material-network
    restart: unless-stopped

networks:
  material-network:
    driver: bridge
